apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logos.fullname" . }}
  labels:
    {{- include "logos.labels" . | nindent 4 }}
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  {{- range $key, $value := .Values.logos.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}